@base_url = https://course-backend-ed2v.onrender.com


### / Route

GET  {{base_url}}

### / heath

GET  {{base_url}}/health


### create new course

POST  {{base_url}}/api/v1/courses
Content-Type: application/json

 {
    "title": "Data Science Fundamentals",
    "instructor": "Dr. Emily Wong",
    "duration": "10 weeks",
    "mode": "offline",
    "description": "Introduction to data analysis, visualization, and machine learning concepts using Python.",
    "prerequisites": "Python programming basics"
  }

### get all the coures
GET {{base_url}}/api/v1/courses
Content-Type: application/json



### get course by id
GET {{base_url}}/api/v1/courses/6862be396c8ed99a065938ca
Content-Type: application/json

### Delete coures by id

DELETE  {{base_url}}/api/v1/courses/6862be396c8ed99a065938ca
Content-Type: application/json